// Pure-logic test runner. `make test` => `swift run CharlieTests`.
print("NotchGeometry")
NotchGeometryTests.all()
print("\nHitState")
HitStateTests.all()
print("\nCreatureGaze")
CreatureGazeTests.all()
print("\nShelfItem")
ShelfItemTests.all()
print("\nPromisePayload")
PromisePayloadTests.all()
print("\nSensorSnapshot")
SensorSnapshotTests.all()
print("\nNowPlaying")
NowPlayingTests.all()
print("\nAgentWatch")
AgentWatchTests.all()
Check.finish()
